=== suyash2389/DVTOPRD/dvreportmodel/resources/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="com.ibm.csi.npm.dvreportinput" 
xmlns:tns="com.ibm.csi.npm.dvreportinput" elementFormDefault="qualified">



    <complexType name="ReporterInput">
    	<sequence>
    		<element name="reporterId" type="int"></element>
    		<element name="widgetConfigInput" type="tns:WidgetConfigInput" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="WidgetConfigInput">
    	<sequence>
    		<element name="widget" type="tns:WidgetInput"></element>
    		<element name="mediator" type="tns:MediatorInput"></element>
    		<element name="title" type="tns:TitleInput" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="WidgetInput">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="type" type="string"></element>
    		<element name="adaptor" type="string" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
    <complexType name="MediatorInput">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="type" type="string"></element>
    	</sequence>
    </complexType>
    
    <complexType name="TitleInput">
    	<sequence>
    		<element name="name" type="string"></element>
    	</sequence>
    </complexType>

    <element name="reporterInput" type="tns:ReporterInput"></element>
</schema>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVLs3DC_Big_1Col_2TopN.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>10291</tns:reporterId>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNTable1</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNMediator1</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>TopNTableTitle1</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
    
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNTable2</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNMediator2</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>TopNTableTitle2</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>DCChart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>DCChartMediator</tns:name>
      <tns:type>Mediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>DCChart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>DCChartMediator</tns:name>
      <tns:type>Mediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>DCChart1</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>DCChartMediator1</tns:name>
      <tns:type>Mediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>DCChart2</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>DCChartMediator2</tns:name>
      <tns:type>Mediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
  
  
  
</tns:reporterInput>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVLs1ChartDrilldown.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>95079</tns:reporterId>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart1</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart1Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>startTime</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
</tns:reporterInput>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVLs_AP_TopN.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>10267</tns:reporterId>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopN1Table</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopN1Mediator</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>TopN1Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopN1Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopN1Mediator</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopN2Table</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopN2Mediator</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>TopN2Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
 
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopN2Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopN2Mediator</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
</tns:reporterInput>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVRs_VOIP_Dashboard.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>95071</tns:reporterId> 
    <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>GTSChart2</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>GTSMediator2</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
    <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>GTSChart4</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>GTSMediator4</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>RatioChart1</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>RatioMediator1</tns:name>
      <tns:type>ratioMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>RatioChart2</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>RatioMediator2</tns:name>
      <tns:type>ratioMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>RatioChart3</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>RatioMediator3</tns:name>
      <tns:type>ratioMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>RatioChart4</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>RatioMediator4</tns:name>
      <tns:type>ratioMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>ResDistribChart1</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>ResDistribMediator1</tns:name>
      <tns:type>resourceDistributionMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>ResDistribChart2</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>ResDistribMediator2</tns:name>
      <tns:type>resourceDistributionMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>ResDistribChart3</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>ResDistribMediator3</tns:name>
      <tns:type>resourceDistributionMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
    <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNTable1</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNMediator1</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNTable2</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNMediator2</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
 
  
</tns:reporterInput>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVLsResDistrib_RST.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>10331</tns:reporterId>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>ResDistribChart1</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>ResDistribMediator1</tns:name>
      <tns:type>resourceDistributionMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>ResDistribChart2</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>ResDistribMediator2</tns:name>
      <tns:type>resourceDistributionMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>statsTable</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcResourceSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>statsTableMediator</tns:name>
      <tns:type>rstMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>reportTableTitle</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
 
</tns:reporterInput>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVLs_BSM_6Chart_6Table.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>10267</tns:reporterId>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Table1</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcResourceSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>Table1Mediator</tns:name>
      <tns:type>rstMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>TableTitle1</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Table2</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcResourceSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>Table2Mediator</tns:name>
      <tns:type>rstMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>TableTitle2</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Table3</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcResourceSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>Table3Mediator</tns:name>
      <tns:type>rstMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>TableTitle3</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Table4</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcResourceSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>Table4Mediator</tns:name>
      <tns:type>rstMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>TableTitle4</tns:name>
 	</tns:title>
       </tns:widgetConfigInput>
     <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Table5</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcResourceSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>Table5Mediator</tns:name>
      <tns:type>rstMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>TableTitle5</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Table6</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcResourceSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>Table6Mediator</tns:name>
      <tns:type>rstMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>TableTitle6</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart1</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart1Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>ChartTitle1</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart2</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart2Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>ChartTitle2</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart3</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart3Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>ChartTitle3</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart4</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart4Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>ChartTitle4</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart5</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart5Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>ChartTitle5</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart6</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart6Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>ChartTitle6</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
 
</tns:reporterInput>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVLs_BSM_6Chart_Small_Drilldown_Titles_LED.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>10267</tns:reporterId>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart1</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart1Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Chart1Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart2</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart2Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Chart2Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart3</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart3Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Chart3Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart4</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart4Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Chart4Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart5</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart5Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Chart5Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart6</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart6Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Chart6Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart1LED</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart1LEDMediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Chart1TitlePlain</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart2LED</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart2LEDMediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Chart2TitlePlain</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart3LED</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart3LEDMediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Chart3TitlePlain</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart4LED</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart4LEDMediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Chart4TitlePlain</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart5LED</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart5LEDMediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Chart5TitlePlain</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart6LED</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart6LEDMediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Chart6titlePlain</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
 
</tns:reporterInput>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVRsMatrix.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>78007</tns:reporterId>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>MatrixTable</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>MatrixAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>MatrixMediator</tns:name>
      <tns:type>MatrixMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>MatrixTitle</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
</tns:reporterInput>
