=== suyash2389/DVTOPRD/dvreportmodel/resources/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="com.ibm.csi.npm.dvreportinput" 
xmlns:tns="com.ibm.csi.npm.dvreportinput" elementFormDefault="qualified">



    <complexType name="ReporterInput">
    	<sequence>
    		<element name="reporterId" type="int"></element>
    		<element name="widgetConfigInput" type="tns:WidgetConfigInput" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="WidgetConfigInput">
    	<sequence>
    		<element name="widget" type="tns:WidgetInput"></element>
    		<element name="mediator" type="tns:MediatorInput"></element>
    		<element name="title" type="tns:TitleInput" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="WidgetInput">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="type" type="string"></element>
    		<element name="adaptor" type="string" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
    <complexType name="MediatorInput">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="type" type="string"></element>
    	</sequence>
    </complexType>
    
    <complexType name="TitleInput">
    	<sequence>
    		<element name="name" type="string"></element>
    	</sequence>
    </complexType>

    <element name="reporterInput" type="tns:ReporterInput"></element>
</schema>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVLsBaseline.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>100000896</tns:reporterId>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>BaselineChart1</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>BaselineMediator1</tns:name>
      <tns:type>baselineMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
</tns:reporterInput>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVLsGroupSummaryTable.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>69143</tns:reporterId>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>GroupSummary1Table</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcGroupSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>groupSummaryTableMediator</tns:name>
      <tns:type>gstMediator</tns:type>
    </tns:mediator>   
    <tns:title>
      <tns:name>reportTableTitle</tns:name>
    </tns:title>  
  </tns:widgetConfigInput> 
</tns:reporterInput>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVLs_RADIUS_Dashboard.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>25770</tns:reporterId>
    <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>GroupSummaryTable</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcGroupSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>GroupSummaryMediator</tns:name>
      <tns:type>gstMediator</tns:type>
    </tns:mediator>   
    <tns:title>
      <tns:name>GroupSummaryTitle</tns:name>
    </tns:title>  
  </tns:widgetConfigInput> 
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>GTS1Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>GTS1Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>GroupTimeSeries1Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>GTS2Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>GTS2Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>GroupTimeSeries2Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopN1Table</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopN1Mediator</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>   
    <tns:title>
      <tns:name>TopN1Title</tns:name>
    </tns:title>  
  </tns:widgetConfigInput>  
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopN2Table</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopN2Mediator</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>   
    <tns:title>
      <tns:name>TopN2Title</tns:name>
    </tns:title>  
  </tns:widgetConfigInput>  
  
    <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Ratio1Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Ratio1Mediator</tns:name>
      <tns:type>ratioMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Ratio1Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Ratio2Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Ratio2Mediator</tns:name>
      <tns:type>ratioMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Ratio2Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>

  </tns:reporterInput>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVLs_AP_6GrpTimeSeries.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>25645</tns:reporterId>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>GroupTimeSeries1Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>GroupTimeSeries1Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>GroupTimeSeries1Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>GroupTimeSeries2Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>GroupTimeSeries2Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>GroupTimeSeries2Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>GroupTimeSeries3Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>GroupTimeSeries3Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>GroupTimeSeries3Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>GroupTimeSeries4Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>GroupTimeSeries4Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>GroupTimeSeries4Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>GroupTimeSeries5Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>GroupTimeSeries5Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>GroupTimeSeries5Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>GroupTimeSeries6Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>GroupTimeSeries6Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>GroupTimeSeries6Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
 
 
  
</tns:reporterInput>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVLs_RADIUS_ThresholdViolation.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>10287</tns:reporterId>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>resourceOverThrTable</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcResourceOverThrTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>resourceOverThrTableMediator</tns:name>
      <tns:type>rttMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>ThresholdViolation1Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
</tns:reporterInput>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVLs_BSM_9Distrib_1Table.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>10267</tns:reporterId>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart1</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart1Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Chart1Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart2</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart2Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Chart2Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart3</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart3Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Chart3Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart4</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart4Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Chart4Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart5</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart5Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Chart5Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart6</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart6Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Chart6Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
    <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart7</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart7Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Chart7Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
    <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart8</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart8Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Chart8Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
    <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart9</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart9Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Chart9Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>MainTable</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcGroupSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>MainTableMediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>MainTableTitle</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  
  
 
</tns:reporterInput>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVLs_BSM_4TopN_1Table.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>10267</tns:reporterId>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNTable1</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNMediator1</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>TopNTableTitle1</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNChart1</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNMediator1</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
    <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNTable2</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNMediator2</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>TopNTableTitle2</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNChart2</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNMediator2</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
    <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNTable3</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNMediator3</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>TopNTableTitle3</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNChart3</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNMediator3</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
    <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNTable4</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNMediator4</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>TopNTableTitle4</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNChart4</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNMediator4</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>MainTable</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcGroupSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>MainTableMediator</tns:name>
      <tns:type>gstMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>MainTableTitle</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
</tns:reporterInput>
