=== suyash2389/DVTOPRD/dvreportmodel/resources/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="com.ibm.csi.npm.dvreportinput" 
xmlns:tns="com.ibm.csi.npm.dvreportinput" elementFormDefault="qualified">



    <complexType name="ReporterInput">
    	<sequence>
    		<element name="reporterId" type="int"></element>
    		<element name="widgetConfigInput" type="tns:WidgetConfigInput" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="WidgetConfigInput">
    	<sequence>
    		<element name="widget" type="tns:WidgetInput"></element>
    		<element name="mediator" type="tns:MediatorInput"></element>
    		<element name="title" type="tns:TitleInput" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="WidgetInput">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="type" type="string"></element>
    		<element name="adaptor" type="string" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
    <complexType name="MediatorInput">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="type" type="string"></element>
    	</sequence>
    </complexType>
    
    <complexType name="TitleInput">
    	<sequence>
    		<element name="name" type="string"></element>
    	</sequence>
    </complexType>

    <element name="reporterInput" type="tns:ReporterInput"></element>
</schema>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVLsRankVariation.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>10268</tns:reporterId>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>RankVariationTable1</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>DVRankVariationTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>RankVariationMediator1</tns:name>
      <tns:type>rankVariationMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>RankVariationChart1</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>RankVariationMediator1</tns:name>
      <tns:type>rankVariationMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>RankVariationTable2</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>DVRankVariationTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>RankVariationMediator2</tns:name>
      <tns:type>rankVariationMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>RankVariationChart2</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>RankVariationMediator2</tns:name>
      <tns:type>rankVariationMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>RankVariationTable3</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>DVRankVariationTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>RankVariationMediator3</tns:name>
      <tns:type>rankVariationMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>RankVariationChart3</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>RankVariationMediator3</tns:name>
      <tns:type>rankVariationMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>RankVariationTable4</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>DVRankVariationTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>RankVariationMediator4</tns:name>
      <tns:type>rankVariationMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>RankVariationChart4</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>RankVariationMediator4</tns:name>
      <tns:type>rankVariationMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>RankVariationTable5</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>DVRankVariationTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>RankVariationMediator5</tns:name>
      <tns:type>rankVariationMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>RankVariationChart5</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>RankVariationMediator5</tns:name>
      <tns:type>rankVariationMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>RankVariationTable6</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>DVRankVariationTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>RankVariationMediator6</tns:name>
      <tns:type>rankVariationMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>RankVariationChart6</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>RankVariationMediator6</tns:name>
      <tns:type>rankVariationMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
</tns:reporterInput>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVLs_AP_ThresholdViolation_DC.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>10287</tns:reporterId>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>PropertyHistory1Table</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcResourceOverThrTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>PropertyHistory1Mediator</tns:name>
      <tns:type>rttMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>ThresholdViolation1Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
		<tns:widget>
			<tns:name>ResTimeSeries1Chart</tns:name>
			<tns:type>chart</tns:type>
		</tns:widget>
		<tns:mediator>
			<tns:name>ResTimeSeries1Mediator</tns:name>
			<tns:type>timeSeriesMediator</tns:type>
		</tns:mediator>
		<tns:title>
			<tns:name>ResTimeSeries1Title</tns:name>
		</tns:title>
	</tns:widgetConfigInput>
	
</tns:reporterInput>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVLsRatio_GST.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>95071</tns:reporterId>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>groupSummaryTable</tns:name>
      <tns:type>table</tns:type>
       <tns:adaptor>PVLcGroupSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>groupSummaryTableMediator</tns:name>
      <tns:type>rgstMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>reportTableTitle</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>RatioChart1</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>RatioMediator1</tns:name>
      <tns:type>ratioMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>RatioChart2</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>RatioMediator2</tns:name>
      <tns:type>ratioMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
</tns:reporterInput>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVLs6ChartDrilldown_2Ratio_6PropDVDrill.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>25641</tns:reporterId>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart1</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart1Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart2</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart2Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart3</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart3Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart4</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart4Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart5</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart5Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Chart6</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Chart6Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>RatioChart1</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>RatioChartMediator1</tns:name>
      <tns:type>ratioMediator</tns:type>
    </tns:mediator>     
  </tns:widgetConfigInput> 
  
    <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>RatioChart2</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>RatioChartMediator2</tns:name>
      <tns:type>ratioMediator</tns:type>
    </tns:mediator>     
  </tns:widgetConfigInput>  
  
</tns:reporterInput>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVLs_AP_ResSummary_w_2ResDistrib.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>10285</tns:reporterId>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>ResDistrib1Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>ResDistrib1Mediator</tns:name>
      <tns:type>resourceDistributionMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>ResDistrib1Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>ResDistrib2Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>ResDistrib2Mediator</tns:name>
      <tns:type>resourceDistributionMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>ResDistrib2Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>ResSummary1Table</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcResourceSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>ResSummary1Mediator</tns:name>
      <tns:type>rstMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>ResSummary1Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>ResSummary2Table</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcResourceSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>ResSummary2Mediator</tns:name>
      <tns:type>rstMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>ResSummary2Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
</tns:reporterInput>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVLs_RADIUS_GroupSummary_w_2Ratio_6GTS.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>69144</tns:reporterId>
  
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>GroupSummary1Table</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcGroupSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>GroupSummary1Mediator</tns:name>
      <tns:type>gstMediator</tns:type>
    </tns:mediator>   
    <tns:title>
      <tns:name>GroupSummary1Title</tns:name>
    </tns:title>  
  </tns:widgetConfigInput> 
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>GTS1Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>GTS1Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>GroupTimeSeries1Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>GTS2Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>GTS2Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>GroupTimeSeries2Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>GTS3Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>GTS3Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>GroupTimeSeries3Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>GTS4Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>GTS4Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>GroupTimeSeries4Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  
   <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>GTS5Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>GTS5Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>GroupTimeSeries5Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
 
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>GTS6Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>GTS6Mediator</tns:name>
      <tns:type>timeSeriesMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>GroupTimeSeries6Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Ratio1Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Ratio1Mediator</tns:name>
      <tns:type>ratioMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Ratio1Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>Ratio2Chart</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>Ratio2Mediator</tns:name>
      <tns:type>ratioMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>Ratio2Title</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
 
</tns:reporterInput>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVLsTopN_6Chart3Row_avg_ratio.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
  <tns:reporterId>10291</tns:reporterId>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNTable1</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNMediator1</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>reportTableTitle1</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNChart1</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNChartMediator1</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>TopNChartTitle1</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNTable2</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNMediator2</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>reportTableTitle2</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNChart2</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNChartMediator2</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>TopNChartTitle2</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNTable3</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNMediator3</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>reportTableTitle3</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNChart3</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNChartMediator3</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>TopNChartTitle3</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNTable4</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNMediator4</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>reportTableTitle4</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNChart4</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNChartMediator4</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>TopNChartTitle4</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNTable5</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNMediator5</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>reportTableTitle5</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNChart5</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNChartMediator5</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>TopNChartTitle5</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNTable6</tns:name>
      <tns:type>table</tns:type>
      <tns:adaptor>PVLcSummaryTableAdaptor</tns:adaptor>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNMediator6</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>reportTableTitle6</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  <tns:widgetConfigInput>
    <tns:widget>
      <tns:name>TopNChart6</tns:name>
      <tns:type>chart</tns:type>
    </tns:widget>
    <tns:mediator>
      <tns:name>TopNChartMediator6</tns:name>
      <tns:type>topnMediator</tns:type>
    </tns:mediator>
    <tns:title>
      <tns:name>TopNChartTitle6</tns:name>
    </tns:title>
  </tns:widgetConfigInput>
  
  
  
 
</tns:reporterInput>

=== suyash2389/DVTOPRD/dvreportmodel/resources/PVLs_AP_Dashboard_5620SAM_Interface.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reporterInput xmlns:tns="com.ibm.csi.npm.dvreportinput"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="com.ibm.csi.npm.dvreportinput input.xsd ">
	<tns:reporterId>25719</tns:reporterId>
	
	<tns:widgetConfigInput>
		<tns:widget>
			<tns:name>ResDistrib1Chart</tns:name>
			<tns:type>chart</tns:type>
		</tns:widget>
		<tns:mediator>
			<tns:name>ResDistrib1Mediator</tns:name>
			<tns:type>resourceDistributionMediator</tns:type>
		</tns:mediator>
		<tns:title>
			<tns:name>ResDistrib1Title</tns:name>
		</tns:title>
	</tns:widgetConfigInput>		

	<tns:widgetConfigInput>
		<tns:widget>
			<tns:name>GroupTimeSeries1Chart</tns:name>
			<tns:type>chart</tns:type>
		</tns:widget>
		<tns:mediator>
			<tns:name>GroupTimeSeries1Mediator</tns:name>
			<tns:type>timeSeriesMediator</tns:type>
		</tns:mediator>
		<tns:title>
			<tns:name>GroupTimeSeries1Title</tns:name>
		</tns:title>
	</tns:widgetConfigInput>

	<tns:widgetConfigInput>
		<tns:widget>
			<tns:name>ResDistrib2Chart</tns:name>
			<tns:type>chart</tns:type>
		</tns:widget>
		<tns:mediator>
			<tns:name>ResDistrib2Mediator</tns:name>
			<tns:type>resourceDistributionMediator</tns:type>
		</tns:mediator>
		<tns:title>
			<tns:name>ResDistrib2Title</tns:name>
		</tns:title>
	</tns:widgetConfigInput>

	<tns:widgetConfigInput>
		<tns:widget>
			<tns:name>GroupTimeSeries2Chart</tns:name>
			<tns:type>chart</tns:type>
		</tns:widget>
		<tns:mediator>
			<tns:name>GroupTimeSeries2Mediator</tns:name>
			<tns:type>timeSeriesMediator</tns:type>
		</tns:mediator>
		<tns:title>
			<tns:name>GroupTimeSeries2Title</tns:name>
		</tns:title>
	</tns:widgetConfigInput>
	
	<tns:widgetConfigInput>
		<tns:widget>
			<tns:name>ResDistrib3Chart</tns:name>
			<tns:type>chart</tns:type>
		</tns:widget>
		<tns:mediator>
			<tns:name>ResDistrib3Mediator</tns:name>
			<tns:type>resourceDistributionMediator</tns:type>
		</tns:mediator>
		<tns:title>
			<tns:name>ResDistrib3Title</tns:name>
		</tns:title>
	</tns:widgetConfigInput>
	

	<tns:widgetConfigInput>
		<tns:widget>
			<tns:name>GroupTimeSeries3Chart</tns:name>
			<tns:type>chart</tns:type>
		</tns:widget>
		<tns:mediator>
			<tns:name>GroupTimeSeries3Mediator</tns:name>
			<tns:type>timeSeriesMediator</tns:type>
		</tns:mediator>
		<tns:title>
			<tns:name>GroupTimeSeries3Title</tns:name>
		</tns:title>
	</tns:widgetConfigInput>

	<tns:widgetConfigInput>
		<tns:widget>
			<tns:name>TopN1Table</tns:name>
			<tns:type>table</tns:type>
			<tns:adaptor>PVLcSummaryTableAdaptor</tns:adaptor>
		</tns:widget>
		<tns:mediator>
			<tns:name>TopN1Mediator</tns:name>
			<tns:type>topnMediator</tns:type>
		</tns:mediator>
		<tns:title>
			<tns:name>TopN1Title</tns:name>
		</tns:title>
	</tns:widgetConfigInput>

	<tns:widgetConfigInput>
		<tns:widget>
			<tns:name>ResDistrib4Chart</tns:name>
			<tns:type>chart</tns:type>
		</tns:widget>
		<tns:mediator>
			<tns:name>ResDistrib4Mediator</tns:name>
			<tns:type>resourceDistributionMediator</tns:type>
		</tns:mediator>
		<tns:title>
			<tns:name>ResDistrib4Title</tns:name>
		</tns:title>
	</tns:widgetConfigInput>

	<tns:widgetConfigInput>
		<tns:widget>
			<tns:name>GroupTimeSeries4Chart</tns:name>
			<tns:type>chart</tns:type>
		</tns:widget>
		<tns:mediator>
			<tns:name>GroupTimeSeries4Mediator</tns:name>
			<tns:type>timeSeriesMediator</tns:type>
		</tns:mediator>
		<tns:title>
			<tns:name>GroupTimeSeries4Title</tns:name>
		</tns:title>
	</tns:widgetConfigInput>
	
	<tns:widgetConfigInput>
		<tns:widget>
			<tns:name>TopN2Table</tns:name>
			<tns:type>table</tns:type>
			<tns:adaptor>PVLcSummaryTableAdaptor</tns:adaptor>
		</tns:widget>
		<tns:mediator>
			<tns:name>TopN2Mediator</tns:name>
			<tns:type>topnMediator</tns:type>
		</tns:mediator>
		<tns:title>
			<tns:name>TopN2Title</tns:name>
		</tns:title>
	</tns:widgetConfigInput>


	<tns:widgetConfigInput>
		<tns:widget>
			<tns:name>ResDistrib5Chart</tns:name>
			<tns:type>chart</tns:type>
		</tns:widget>
		<tns:mediator>
			<tns:name>ResDistrib5Mediator</tns:name>
			<tns:type>resourceDistributionMediator</tns:type>
		</tns:mediator>
		<tns:title>
			<tns:name>ResDistrib5Title</tns:name>
		</tns:title>
	</tns:widgetConfigInput>

	<tns:widgetConfigInput>
		<tns:widget>
			<tns:name>ResDistrib6Chart</tns:name>
			<tns:type>chart</tns:type>
		</tns:widget>
		<tns:mediator>
			<tns:name>ResDistrib6Mediator</tns:name>
			<tns:type>resourceDistributionMediator</tns:type>
		</tns:mediator>
		<tns:title>
			<tns:name>ResDistrib6Title</tns:name>
		</tns:title>
	</tns:widgetConfigInput>

	<tns:widgetConfigInput>
		<tns:widget>
			<tns:name>ResDistrib7Chart</tns:name>
			<tns:type>chart</tns:type>
		</tns:widget>
		<tns:mediator>
			<tns:name>ResDistrib7Mediator</tns:name>
			<tns:type>resourceDistributionMediator</tns:type>
		</tns:mediator>
		<tns:title>
			<tns:name>ResDistrib7Title</tns:name>
		</tns:title>
	</tns:widgetConfigInput>
</tns:reporterInput>
